name: Daily Ad Insights

on:
  schedule:
    # 매일 오전 9시 (한국 시간 = UTC 0시)
    - cron: '0 0 * * 1-5'
  workflow_dispatch:  # 수동 실행 버튼

jobs:
  run-agent:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3
    
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 패키지 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 인사이트 에이전트 실행
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
      run: |
        python advanced_ad_insights_agent.py
